package config

var AvailableRecipes = []string{
	// List out all the recipe names from cube_recipes.go
	"Reroll GrandCharms",
	"Reroll Specific",
	"Token of Absolution",
	"Upgrade El",
	"Upgrade Eld",
	"Upgrade Tir",
	"Upgrade Nef",
	"Upgrade Eth",
	"Upgrade Ith",
	"Upgrade Tal",
	"Upgrade Ral",
	"Upgrade Ort",
	"Upgrade Thul",
	"Upgrade Amn",
	"Upgrade Sol",
	"Upgrade Shael",
	"Upgrade Dol",
	"Upgrade Hel",
	"Upgrade Io",
	"Upgrade Lum",
	"Upgrade Ko",
	"Upgrade Fal",
	"Upgrade Lem",
	"Upgrade Pul",
	"Upgrade Um",
	"Upgrade Mal",
	"Upgrade Ist",
	"Upgrade Gul",
	"Upgrade Vex",
	"Upgrade Ohm",
	"Upgrade Lo",
	"Upgrade Sur",
	"Upgrade Ber",
	"Upgrade Jah",
	"Upgrade Cham",
	"Flawed Amethyst",
	"Flawed Diamond",
	"Flawed Emerald",
	"Flawed Ruby",
	"Flawed Sapphire",
	"Flawed Topaz",
	"Flawed Skull",
	"Amethyst",
	"Diamond",
	"Emerald",
	"Ruby",
	"Sapphire",
	"Topaz",
	"Skull",
	"Flawless Amethyst",
	"Flawless Diamond",
	"Flawless Emerald",
	"Flawless Ruby",
	"Flawless Sapphire",
	"Flawless Topaz",
	"Flawless Skull",
	"Perfect Amethyst",
	"Perfect Diamond",
	"Perfect Emerald",
	"Perfect Ruby",
	"Perfect Sapphire",
	"Perfect Topaz",
	"Perfect Skull",
	"Add Sockets to Weapon",
	"Add Sockets to Armor",
	"Add Sockets to Helm",
	"Add Sockets to Shield",
	"Blood Amulet",
	"Blood Ring",
	"Blood Gloves (VampireboneGloves)",
	"Blood Boots",
	"Blood Belt (MithrilCoil)",
	"Blood Helm (Armet)",
	"Blood Armor",
	"Blood Weapon",
	"Safety Shield",
	"Safety Armor",
	"Safety Boots",
	"Blood Gloves (SharkskinGloves)",
	"Blood Belt (MeshBelt)",
	"Safety Helm",
	"Hitpower Gloves (HeavyBracers)",
	"Hitpower Boots",
	"Caster Belt (SharkskinBelt)",
	"Hitpower Helm",
	"Hitpower Armor",
	"Caster Amulet",
	"Caster Ring",
	"Caster Belt (VampirefangBelt)",
	"Caster Boots",
	"MagicWirtsLegStep1",
	"MagicWirtsLegStep2",
}
